logging:
  level:
    org:
    hibernate:
      SQL: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hr?serverTimezone=UTC
    username: admin
    password: password
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
      format_sql: true


  jackson:
    serialization:
      fail-on-empty-beans: false

  hibernate:
      ddl-auto: none

